### ISSUE TITLE
HIDE_ATTRIBUTES set by default to item buttons

### ISSUE THREAD

**Issue by randombyte-developer** [CeresPowered/Menu#6]
To prevent showing the hover text with the item's attributes(like with weapons -> damage values) I suggest setting `Keys.HIDE_ATTRIBUTES` by default to true. Otherwise it has to be done by setting it to the icon itemstack directly and then pass it to the button builder.

**Comment by SocraticPhoenix** [comment]
Fixed (may not be committed yet - will be soon though)
